replicaCount: 2

image:
  repository: 779846808506.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: "2ce48e201e98fc7d28a252c186722cb554403683"

containerPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80