replicaCount: 2

image:
  repository: 779846808506.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: "295759dec6fc7b61edcb5a40162ff258550ddce4"

containerPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80