replicaCount: 1

image:
  repository: 779846808506.dkr.ecr.ap-south-1.amazonaws.com/transaction-service
  tag: "2ce48e201e98fc7d28a252c186722cb554403683"
  pullPolicy: IfNotPresent

service:
  port: 3001
