replicaCount: 1

image:
  repository: 779846808506.dkr.ecr.ap-south-1.amazonaws.com/transaction-service
  tag: "caaa7b30ad36d194396bfa47e1afeb5ef0f0ce5d"
  pullPolicy: IfNotPresent

service:
  port: 3001
