replicaCount: 2

image:
  repository: 779846808506.dkr.ecr.ap-south-1.amazonaws.com/legacy-service
  tag: "b9e34a5c6188851bbed66010164bb6aa4378cf59"
  pullPolicy: IfNotPresent

service:
  port: 3000
  
autoscaling:
  enabled: false
